# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


kvh_read <- function(fn, comment_str = "", strip_white = FALSE, skip_blank = FALSE, split_str = "", follow_url = FALSE) {
    .Call(`_kvh_kvh_read`, fn, comment_str, strip_white, skip_blank, split_str, follow_url)
}