# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read a KVH file
#'
#' @param fn Path to the KVH file.
#' @param comment_str String to use for comments.
#' @param strip_white Boolean. If `FALSE`, whitespace is not stripped from the
#'   comment string.
#' @param skip_blank Boolean. If `FALSE`, blank lines are not skipped.
#' @param split_str String to use to split the data.
#' @param follow_url Boolean. If `FALSE`, the function assumes that the file is
#'   a local file and does not follow a URL.
#'
#' @return A list of data frames.
#' @export
kvh_read <- function(fn, comment_str = "", strip_white = FALSE, skip_blank = FALSE, split_str = "", follow_url = FALSE) {
    .Call(`_kvh_kvh_read`, fn, comment_str, strip_white, skip_blank, split_str, follow_url)
}