#!/usr/bin/env python3
"""Root-exclusive full-state editing context memory probe; never updates weights."""
from __future__ import annotations
import argparse,fcntl,hashlib,json,math,os,sys,time
from pathlib import Path
HERE=Path(__file__).resolve().parent;sys.path.insert(0,str(HERE/'packages/sepalith/src'))
EXPECTED_PARAMS=2_516_756_480;EXPECTED_TENSORS=381;CAPS=(2048,4096,8192,16384,32768)
HELD_SOURCE_FDS=[];HELD_SOURCE_PATHS=[]
def require(v,m):
 if not v:raise ValueError(m)
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb')as f:
  for b in iter(lambda:f.read(8<<20),b''):h.update(b)
 return h.hexdigest()
def canonical(v):return json.dumps(v,sort_keys=True,separators=(',',':'),allow_nan=False).encode()
def fingerprint(s):return {k:int(getattr(s,k))for k in ('st_dev','st_ino','st_size','st_mtime_ns','st_ctime_ns')}
def verify_source(path):
 path=Path(path).resolve();root=path.parent;value=json.loads(path.read_text());require(value.get('schema')=='sepalith.sft11.full-weight-edit-context-profile-source.v1','source manifest schema differs');records=value.get('files');require(isinstance(records,list)and records,'source manifest files missing')
 seen=set()
 for item in records:
  rel=item.get('path');require(isinstance(rel,str)and rel and rel not in seen,'source manifest path differs');seen.add(rel);p=(root/rel).resolve();require(p.is_relative_to(root)and p.is_file()and not p.is_symlink(),'source path is unsafe');fd=os.open(p,os.O_RDONLY|os.O_CLOEXEC);before=os.fstat(fd);h=hashlib.sha256();n=0
  while True:
   b=os.read(fd,1<<20)
   if not b:break
   h.update(b);n+=len(b)
  after=os.fstat(fd);require(fingerprint(before)==fingerprint(after)and n==item.get('bytes')and h.hexdigest()==item.get('sha256'),'source file identity differs');os.lseek(fd,0,os.SEEK_SET);HELD_SOURCE_FDS.append(fd);HELD_SOURCE_PATHS.append((p,fingerprint(after)))
 return {'files':len(records),'manifest_sha256':sha(path)}
def verify_held_sources():
 require(len(HELD_SOURCE_FDS)==len(HELD_SOURCE_PATHS)and HELD_SOURCE_FDS,'source descriptors missing')
 for fd,(path,expected) in zip(HELD_SOURCE_FDS,HELD_SOURCE_PATHS):require(fingerprint(os.fstat(fd))==expected==fingerprint(path.stat()),'source path changed after verification')
def validate_fixture(path,expected_sha,cap):
 path=Path(path);require(sha(path)==expected_sha,'fixture hash differs');lines=[x for x in path.read_text().splitlines()if x];require(len(lines)==1,'profile requires exactly one row');r=json.loads(lines[0]);ids=r.get('input_ids');labels=r.get('labels');mask=r.get('attention_mask');require(isinstance(ids,list)and len(ids)==len(labels)==len(mask)and 4<=len(ids)<=cap,'fixture token arrays differ');require(ids[0]==0 and ids[-1]==1 and labels[-1]==1 and all(x==1 for x in mask),'fixture BOS/EOS/mask differs');first=next((i for i,x in enumerate(labels)if x!=-100),None);require(first is not None and first>0 and labels[:first]==[-100]*first and labels[first:]==ids[first:],'fixture is not exact target-only suffix supervision');require(r.get('supervised_tokens')==len(ids)-first,'fixture supervised count differs');return r,first
def validate_attestation(checkpoint,manifest):
 raw=os.environ.get('SEPALITH_NATIVE_STAGE_ATTESTATION');require(raw,'native checkpoint attestation missing');env=json.loads(raw);records={x['path']:x for x in env.get('files',[])};expected={**manifest['files'],'campaign-manifest.json':{'bytes':(checkpoint/'campaign-manifest.json').stat().st_size,'sha256':sha(checkpoint/'campaign-manifest.json')}}
 for rel,item in expected.items():
  p=checkpoint/rel;record=records.get(str(p.resolve()));require(record is not None and record.get('sha256')==item['sha256']and record.get('bytes')==item['bytes'],'checkpoint file lacks exact attestation');fd=record.get('fd');require(type(fd)is int,'checkpoint attestation fd differs');require(fingerprint(os.fstat(fd))==fingerprint(p.stat())==record.get('fingerprint'),'checkpoint attested inode changed')
 return {'files':len(expected),'payload_bytes':sum(x['bytes']for x in manifest['files'].values())}
def load_admission(path,checkpoint,fixture,cap,source_manifest):
 p=Path(path);v=json.loads(p.read_text());require(v.get('schema')=='sepalith.sft11.full-weight-edit-context-profile-admission.v1'and v.get('status')=='admitted'and v.get('launch_authorized')is True,'profile is not root-admitted');require(v.get('cap')==cap and Path(v.get('checkpoint','')).resolve()==checkpoint.resolve()and Path(v.get('fixture','')).resolve()==fixture.resolve(),'profile admission paths differ');require(v.get('checkpoint_manifest_sha256')==sha(checkpoint/'campaign-manifest.json')and v.get('fixture_sha256')==sha(fixture)and v.get('source_manifest_sha256')==sha(source_manifest),'profile admission identity differs');return {'path':str(p.resolve()),'sha256':sha(p)}
def sample_parameters(named,torch):
 out={}
 for name,p in named:
  n=min(16,p.numel());idx=(torch.arange(n,device=p.device,dtype=torch.int64)*max(0,p.numel()-1))//max(1,n-1);out[name]=p.detach().view(-1)[idx].clone()
 return out
def rng_digest(torch):return {'cpu':hashlib.sha256(torch.get_rng_state().cpu().numpy().tobytes()).hexdigest(),'cuda':[hashlib.sha256(x.cpu().numpy().tobytes()).hexdigest()for x in torch.cuda.get_rng_state_all()]}
def optimizer_state(optimizer,torch):
 values=[x for state in optimizer.state.values()for x in state.values()if torch.is_tensor(x)];return {'tensors':len(values),'bytes':sum(x.numel()*x.element_size()for x in values),'floating_fp32':all(not x.is_floating_point()or x.dtype==torch.float32 for x in values),'finite':all(not x.is_floating_point()or bool(torch.isfinite(x).all().item())for x in values)}
def main():
 p=argparse.ArgumentParser();p.add_argument('--checkpoint',type=Path,required=True);p.add_argument('--checkpoint-manifest-sha256',required=True);p.add_argument('--fixture',type=Path,required=True);p.add_argument('--fixture-sha256',required=True);p.add_argument('--cap',type=int,choices=CAPS,required=True);p.add_argument('--source-manifest',type=Path,required=True);p.add_argument('--admission',type=Path,required=True);p.add_argument('--report',type=Path,required=True);a=p.parse_args();require(not a.report.exists(),'report path must be fresh');require(sha(a.source_manifest)==json.loads(a.admission.read_text()).get('source_manifest_sha256'),'runtime source differs');source_audit=verify_source(a.source_manifest);manifest_path=a.checkpoint/'campaign-manifest.json';require(manifest_path.is_file()and sha(manifest_path)==a.checkpoint_manifest_sha256,'checkpoint manifest differs');manifest=json.loads(manifest_path.read_text());require(manifest.get('full')is True and manifest.get('checkpoint_kind')=='full_weights'and {'model.safetensors','optimizer.pt','scheduler.pt','rng_state.pth'}<=set(manifest.get('files',{})),'checkpoint is not complete full state');admission=load_admission(a.admission,a.checkpoint,a.fixture,a.cap,a.source_manifest);attestation=validate_attestation(a.checkpoint,manifest);row,target_start=validate_fixture(a.fixture,a.fixture_sha256,a.cap)
 os.environ['UNSLOTH_RETURN_LOGITS']='0';from unsloth import FastLanguageModel;import torch,transformers;from transformers.trainer import check_torch_load_is_safe;from full_weight_optimizer import OptimizerConfig,build_full_weight_optimizer;from saved_precision import restore_saved_fp32;from campaign_tokenizer_contract import load_pinned_reference_tokenizer;from trainer_tokenizer_alignment import restore_trainer_eog_alignment,embedding_identity,assert_runtime_tokenizer;verify_held_sources()
 require(transformers.__version__=='5.5.0'and torch.__version__.startswith('2.11.0'),'profile runtime version differs');require(torch.cuda.is_available()and torch.cuda.device_count()==1,'exactly one root-owned CUDA device required');torch.cuda.reset_peak_memory_stats();started=time.time();model,tokenizer=FastLanguageModel.from_pretrained(model_name=str(a.checkpoint),max_seq_length=a.cap,dtype=torch.bfloat16,load_in_4bit=False,full_finetuning=True,float32_mixed_precision=False,fast_inference=False,trust_remote_code=False,use_gradient_checkpointing=True);reference=load_pinned_reference_tokenizer(a.checkpoint);repair=restore_trainer_eog_alignment(model,tokenizer,reference);emb=embedding_identity(model);assert_runtime_tokenizer(model,tokenizer,reference,emb,'post_load');model.config.use_cache=False
 try:FastLanguageModel.for_training(model,use_gradient_checkpointing=True)
 except TypeError:FastLanguageModel.for_training(model)
 repair=restore_trainer_eog_alignment(model,tokenizer,reference);assert_runtime_tokenizer(model,tokenizer,reference,emb,'post_for_training')
 try:model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={'use_reentrant':False})
 except (AttributeError,TypeError):pass
 precision=restore_saved_fp32(model,a.checkpoint/'model.safetensors');model.train();require(getattr(model,'is_gradient_checkpointing',True) is True,'gradient checkpointing is not active');named=list(model.named_parameters());require(len(named)==EXPECTED_TENSORS and sum(x.numel()for _,x in named)==EXPECTED_PARAMS and all(x.requires_grad for _,x in named),'full-weight inventory differs');optimizer_config=manifest['identity']['policy']['optimizer'].copy();optimizer_config.pop('arm',None);optimizer,dispatch=build_full_weight_optimizer(model,OptimizerConfig(arm=manifest['identity']['policy']['optimizer']['arm'],**optimizer_config));memory_after_construct={'allocated':torch.cuda.memory_allocated(),'reserved':torch.cuda.memory_reserved()};check_torch_load_is_safe();state=torch.load(a.checkpoint/'optimizer.pt',map_location='cpu',weights_only=True);optimizer.load_state_dict(state);del state;opt_audit=optimizer_state(optimizer,torch);require(opt_audit['floating_fp32']and opt_audit['finite'],'full optimizer state differs');memory_optimizer_live={'allocated':torch.cuda.memory_allocated(),'reserved':torch.cuda.memory_reserved()}
 check_torch_load_is_safe();scheduler_state=torch.load(a.checkpoint/'scheduler.pt',map_location='cpu',weights_only=True);require(isinstance(scheduler_state,dict)and type(scheduler_state.get('last_epoch'))is int,'checkpoint scheduler state differs');check_torch_load_is_safe();saved_rng=torch.load(a.checkpoint/'rng_state.pth',map_location='cpu',weights_only=True);torch.set_rng_state(saved_rng['cpu']);cuda_state=saved_rng.get('cuda') or saved_rng.get('cuda_rng_state');require(cuda_state is not None,'checkpoint CUDA RNG state missing');torch.cuda.set_rng_state_all(cuda_state if isinstance(cuda_state,list)else[cuda_state]);rng_before=rng_digest(torch);samples=sample_parameters(named,torch);device=next(model.parameters()).device;ids=torch.tensor([row['input_ids']],dtype=torch.long,device=device);labels=torch.tensor([row['labels']],dtype=torch.long,device=device);mask=torch.ones_like(ids);optimizer.zero_grad(set_to_none=True);torch.cuda.synchronize();t=time.time();out=model(input_ids=ids,attention_mask=mask,labels=labels,use_cache=False);require(out.loss is not None and bool(torch.isfinite(out.loss).item()),'profile loss is nonfinite');out.loss.backward();torch.cuda.synchronize();fb=time.time()-t;finite=nonzero=0
 for _,param in named:require(param.grad is not None and bool(torch.isfinite(param.grad).all().item()),'profile gradient missing/nonfinite');finite+=1;nonzero+=int(bool(param.grad.abs().max().item()>0))
 require(finite==nonzero==EXPECTED_TENSORS,'profile gradient coverage differs');unchanged=all(torch.equal(samples[n],sample_parameters([(n,p)],torch)[n])for n,p in named);require(unchanged,'profile changed parent parameters without optimizer step');rng_after=rng_digest(torch);free_after,total_device=torch.cuda.mem_get_info();torch.set_rng_state(saved_rng['cpu']);torch.cuda.set_rng_state_all(cuda_state if isinstance(cuda_state,list)else[cuda_state]);rng_restored=rng_digest(torch);require(rng_restored==rng_before,'profile failed to restore checkpoint RNG');verify_held_sources();report={'schema':'sepalith.sft11.full-weight-edit-context-profile.v1','status':'completed_no_optimizer_update','cap':a.cap,'row_id':row['row_id'],'sequence_tokens':len(row['input_ids']),'supervised_tokens':len(row['input_ids'])-target_start,'source':source_audit,'checkpoint':str(a.checkpoint.resolve()),'checkpoint_manifest_sha256':a.checkpoint_manifest_sha256,'fixture_sha256':a.fixture_sha256,'admission':admission,'attestation':attestation,'full_finetuning':True,'load_in_4bit':False,'trainable_parameters':EXPECTED_PARAMS,'trainable_parameter_tensors':EXPECTED_TENSORS,'optimizer_dispatch':dispatch,'optimizer_state':opt_audit,'scheduler_state':{'last_epoch':scheduler_state['last_epoch'],'step_count':scheduler_state.get('_step_count')},'saved_precision':precision,'gradient_checkpointing':{'requested':True,'use_reentrant':False},'forward_backward_seconds':fb,'loss':float(out.loss.detach().cpu()),'finite_gradient_tensors':finite,'nonzero_gradient_tensors':nonzero,'optimizer_step_called':False,'parameters_unchanged':unchanged,'rng_before':rng_before,'rng_after_profile':rng_after,'rng_restored':rng_restored,'memory':{'after_optimizer_construct':memory_after_construct,'optimizer_state_live':memory_optimizer_live,'peak_allocated':torch.cuda.max_memory_allocated(),'peak_reserved':torch.cuda.max_memory_reserved(),'free_after':int(free_after),'device_total':int(total_device)},'elapsed_seconds':time.time()-started,'quality_evaluation':False};a.report.parent.mkdir(parents=True,exist_ok=True);a.report.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n');print(json.dumps(report,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
