#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
P=Path(__file__).parent
t=json.load(open(P/'token-audit.json'));trade=json.load(open(P/'token-tradeoff.json'));b=json.load(open(P/'notebook/benchmark.json'))
provider=json.load(open(P.parent/'r2-serving-semantic-provider-v3/notebook/census-screen.json'))
rows=t['rows'];over16=[r for r in rows if not r['fits_16k']];over32=[r for r in rows if not r['fits_32k']]
provider_by={r['row_id']:r for r in provider['rows']}
out={'schema':'sepalith.run06.full_document_context_audit.v1','status':'complete_review_only','denominator':128,'analyzer_supported':49,'analyzer_holds':79,'full_document':{'fits_16k':42,'fits_32k':47,'over_32k':2,'helper_fits_16k':6,'helper_denominator':8,'helper_fits_32k':8,'token_distributions':t['distributions'],'all_full_buffer_hashes_and_global_ranges_exact':all(r['source_reapplication_exact'] and r['replacement_range']['content_sha256']==r['preedit_sha256'] and r['replacement_range']['start']==r['cursor'] for r in rows)},'hybrid_without_target_truncation':{'at_16k':42+sum(provider_by[r['row_id']]['status']=='supported' for r in over16),'at_32k':47+sum(provider_by[r['row_id']]['status']=='supported' for r in over32),'explanation':'Use full document when it fits; for over-budget rows only, use the existing complete-target-span bounded selector after semantic support. No target is truncated.'},'provider_v3_comparison':{'supported':30,'analyzer_supported_denominator':49,'helper_exact':2,'helper_denominator':8,'full_document_token_overhead_on_same_30_supported':{k:v for k,v in trade.items() if k not in ('rows','schema')}},'notebook_latency':{'full_document_49x10':b,'provider_v3_prior_same49_one_pass_elapsed_ms':provider['elapsed_ms'],'comparison_limitation':'Full-document timing repeats 10 times per row; provider v3 reference is one prior same-host pass, so this is descriptive rather than a controlled throughput benchmark.'},'limitations':['Full-document prompt inclusion proves same-file helper presence, not that external package namespaces/imports are resolved at prediction time.','Two target-only documents exceed 32K (59,183 and 47,452 total sequence tokens); full-document-only mode cannot preserve them within 32K.','Context-window fit is token accounting, not GPU memory, latency, or model-quality evidence.','The frozen 49 rows are analyzer-supported preparation rows; root training admission remains required.'],'rows_over_16k':[{'row_id':r['row_id'],'sequence_tokens':r['sequence_tokens'],'target_tokens':r['target_tokens'],'helper':bool(r['helper_spans']),'provider_v3_status':provider_by[r['row_id']]['status']} for r in over16]}
(P/'analysis.json').write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps({k:v for k,v in out.items() if k not in ('rows_over_16k','limitations')},indent=2))
