# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read a file from the KVH server
#'
#' @param fn The filename on the server
#' @param comment_str The comment string
#' @param strip_white Whether to strip white space from the comment string
#' @param skip_blank Whether to skip blank lines in the comment string
#' @param split_str The string to split on
#' @param follow_url Whether to follow a URL
#'
#' @return The contents of the file
#'
#' @export
kvh_read <- function(fn, comment_str = "", strip_white = FALSE, skip_blank = FALSE, split_str = "", follow_url = FALSE) {
    .Call(`_kvh_kvh_read`, fn, comment_str, strip_white, skip_blank, split_str, follow_url)
}