# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read a file from the KVH server
#'
#' @param fn The filename on the server
#' @param comment_str If `fn` is a directory, the path to the
#'   comment file
#' @param strip_white If `fn` is a directory, whether to strip
#'   whitespace from the comment file
#' @param skip_blank If `fn` is a directory, whether to skip
#'   blank lines in the comment file
#' @param split_str If `fn` is a directory, whether to split the
#'   comment file into multiple files
#' @param follow_url If `fn` is a directory, whether to follow
#'   URLs in the comment file
#'
#' @return A list of lines from the file
#'
#' @export
kvh_read <- function(fn, comment_str = "", strip_white = FALSE, skip_blank = FALSE, split_str = "", follow_url = FALSE) {
    .Call(`_kvh_kvh_read`, fn, comment_str, strip_white, skip_blank, split_str, follow_url)
}