# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read a KVH file
#'
#' @param fn The filename of the KVH file to read.
#' @param comment_str The string used to separate comments in the file.
#' @param strip_white Whether to remove leading and trailing white space from
#'   each line.
#' @param skip_blank Whether to skip blank lines.
#' @param split_str The string used to separate fields in a line.
#' @param follow_url Whether to follow URLs in the file.
#'
#' @return A list of strings, one per line in the file.
#'
#' @noRd
kvh_read <- function(fn, comment_str = "", strip_white = FALSE, skip_blank = FALSE, split_str = "", follow_url = FALSE) {
    .Call(`_kvh_kvh_read`, fn, comment_str, strip_white, skip_blank, split_str, follow_url)
}