#!/usr/bin/env python3
import collections,json,statistics,sys
from pathlib import Path
from tokenizers import Tokenizer
base=Path(sys.argv[1]);out=Path(__file__).parent;prep=base/'prepared-02';cand=base/'candidates-01'
def load(path):return [json.loads(x) for x in path.open() if x.strip()]
pred=load(prep/'prediction-inputs.jsonl');preholds=load(prep/'preparation-holds.jsonl');render=load(base/'rendered-03.jsonl');supported=[x for x in render if x['bounded_status']=='supported'];tok=Tokenizer.from_file('/home/m0hawk/.local/state/sepalith/campaign-20260915/models/SFT-primary-step1000-theta0/tokenizer.json');full=tok.encode_batch([x['full_prompt'] for x in supported],add_special_tokens=False);bounded=tok.encode_batch([x['bounded_prompt'] for x in supported],add_special_tokens=False);extra=[len(a.ids)-len(b.ids) for a,b in zip(full,bounded)];ratio=[len(a.ids)/len(b.ids) for a,b in zip(full,bounded)]
profiles={}
for cap in (16384,32768):
 ps=load(cand/f'profiles-{cap}.jsonl');hs=load(cand/f'holds-{cap}.jsonl');profiles[str(cap)]={'candidate_rows':len(ps),'holds_including_preparation':len(hs)+len(preholds),'mode_counts':dict(collections.Counter(x['mode'] for x in ps)),'helper_candidates':sum(x['helper_count']>0 for x in ps),'prompt_tokens':{'min':min(x['prompt_tokens'] for x in ps),'median':statistics.median(x['prompt_tokens'] for x in ps),'mean':statistics.fmean(x['prompt_tokens'] for x in ps),'max':max(x['prompt_tokens'] for x in ps)},'sequence_tokens_max':max(x['sequence_tokens'] for x in ps),'target_tokens_max':max(x['target_tokens'] for x in ps),'hold_reasons':dict(collections.Counter([x['reason'] for x in hs]+['invalid_geometry']*len(preholds)))}
analysis={'schema':'sepalith.dat10.semantic763.context_analysis.v1','denominator':763,'reconstructed':762,'invalid_geometry':1,'same_file_helper_rows':142,'external_namespace_import_provider_unavailable':140,'unicode_rows_reconstructed':sum(any(ord(c)>127 for c in x['preedit_text']) for x in pred),'crlf_rows_reconstructed':sum(x['document_eol']=='crlf' for x in pred),'actual_provider_bounded_supported':len(supported),'full_vs_actual_provider_on_bounded_supported':{'denominator':len(extra),'extra_prompt_tokens':{'min':min(extra),'median':statistics.median(extra),'mean':statistics.fmean(extra),'max':max(extra)},'ratio':{'min':min(ratio),'median':statistics.median(ratio),'mean':statistics.fmean(ratio),'max':max(ratio)}},'profiles':profiles,'cohort_local_duplicate_prompt_target':0,'cohort_local_prompt_target_contradictions':0,'cross_corpus_dedup':'pending root union review','selection_target_or_gold_used':False,'training_admission':False};(out/'analysis.json').write_text(json.dumps(analysis,indent=2,sort_keys=True)+'\n');print(json.dumps(analysis,sort_keys=True))
