# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read a file from a URL
#'
#' @param fn A character string with the URL of the file to be read.
#' @param comment_str A character string with the comment to be added to the
#'   file.
#' @param strip_white A logical value indicating whether to strip white
#'   space from the beginning and end of each line.
#' @param skip_blank A logical value indicating whether to skip blank lines
#'   at the beginning of the file.
#' @param split_str A character string with the string to split the file
#'   into multiple chunks.
#' @param follow_url A logical value indicating whether to follow the URL
#'   and download the file.
#'
#' @return A character string with the contents of the file.
#'
#' @export
kvh_read <- function(fn, comment_str = "", strip_white = FALSE, skip_blank = FALSE, split_str = "", follow_url = FALSE) {
    .Call(`_kvh_kvh_read`, fn, comment_str, strip_white, skip_blank, split_str, follow_url)
}