from pathlib import Path
import json,hashlib,subprocess,os,time,re,collections,shutil
P=Path(__file__).resolve().parent;R=P/'remote';D=P/'desktop';ROOT=P.parent/'lead/remote-auto350-c'
def load(p):return json.loads(p.read_text())
def rows(p):return [json.loads(s) for s in p.read_text().splitlines() if s.strip()]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,x):(P/n).write_text(json.dumps(x,indent=2)+'\n')
ev=rows(R/'harness-events.jsonl');g=rows(D/'gateway-events.jsonl');f=rows(R/'renderer-frames.jsonl')
parsed=load(P/'buffer-parse.json')['rows']
ids=[x['requestId'] for x in g if x.get('event')=='request_started' and x.get('path')=='/completion'];life=[]
for id in ids:
 a=[x for x in g if x.get('requestId')==id]
 def event(kind,path=None):return next((x for x in a if x['event']==kind and (path is None or x.get('path')==path)),None)
 d=event('backend_dispatched','/completion');r=event('backend_transport_released','/completion');cancel=event('request_cancelled');release=event('request_released');response=event('response_forwarded')
 cancel_phase=('before_completion_dispatch' if not d else 'after_backend_response_complete' if r and cancel and int(r['monotonicNs'])<int(cancel['monotonicNs']) else 'after_dispatch_before_transport_release') if cancel else None
 life.append({'request_id':id,'dispatch_sequence':d['dispatchSequence'] if d else None,'request_bytes':d['requestBytes'] if d else release.get('requestBytes'),'request_body_sha256':d['requestBodySha256'] if d else None,'dispatch_utc':d['utc'] if d else None,'cancelled':cancel is not None,'cancellation_phase':cancel_phase,'response_status':response.get('status') if response else None,'response_bytes':r['responseBytes'] if r else None,'transport_release_reason':r['reason'] if r else None,'dispatch_to_transport_release_ms':(int(r['monotonicNs'])-int(d['monotonicNs']))/1e6 if d and r else None,'cancel_to_transport_release_ms':(int(r['monotonicNs'])-int(cancel['monotonicNs']))/1e6 if cancel_phase=='after_dispatch_before_transport_release' else None,'request_released':release is not None,'native_task_release_proven':False,'rows':a})
text=(D/'native.log').read_text();proc=re.findall(r'task (\d+) \| processing task',text);released=re.findall(r'task (\d+) \| stop processing',text);times=[float(x) for x in re.findall(r'total time =\s*([\d.]+) ms',text)]
observed=next(x for x in ev if x['kind']=='auto_cancel_dispatch_observed');invalid=next(x for x in ev if x['kind']=='auto_invalidated');keyboard=next(x for x in rows(R/'renderer-inputs.jsonl') if x['input_id']=='typing-cancel-9')
ca=next(x for x in life if x['request_id']==observed['observation']['completionId']);assert ca['dispatch_sequence']==observed['observation']['dispatchSequence'] and ca['cancelled']
save('lifecycle-review.json',{'gateway_completion_requests':len(ids),'dispatches':sum(x['dispatch_sequence'] is not None for x in life),'response200':sum(x['response_status']==200 for x in life),'requester_disconnected':sum(x['cancelled'] for x in life),'all_gateway_requests_released':all(x['request_released'] for x in life),'requests':life,'native':{'processing_task_ids':proc,'released_task_ids':released,'counts_and_id_sets_match':collections.Counter(proc)==collections.Counter(released),'explicit_cancellation_lines':[s for s in text.splitlines() if re.search(r'cancel|abort|disconnec',s,re.I)],'native_total_compute_ms_per_task':times,'native_total_compute_ms_sum':sum(times),'scope':'Native timings measure native prompt/eval work, not editor latency. Gateway UUID to native task ID mapping is absent. Release counts do not prove cancellation savings.','offload43of43':'offloaded 43/43 layers to GPU' in text,'context4096':bool(re.search(r'n_ctx\s*= 4096',text))},'cancel_window':{'observed':observed,'keyboard':keyboard,'invalidated':invalid,'notebook_observation_to_keyboard_ms':keyboard['epoch_ms']-observed['epoch_ms'],'notebook_observation_to_invalidation_event_ms':invalid['epoch_ms']-observed['epoch_ms'],'same_request_gateway_cancel':True,'native_cancel_proven':False,'scope':'Actual keyboard edit after observed HTTP dispatch; cross-host clocks are not subtracted.'},'desktop_terminal':load(D/'terminal.json')})
# Metadata and bounded source files only. Model/library bytes are not read.
(P/'root-inputs').mkdir(exist_ok=True);rootpins=[]
for name in ['binding.json','root-preflight.json','root-launch.json','manifest.json','vsix-identity.json','notebook-capsule/capsule-manifest.json']:
 q=ROOT/name;t=P/'root-inputs'/name.replace('/','--');shutil.copyfile(q,t);rootpins.append({'source':str(q),'copy':str(t.relative_to(P)),'sha256':sha(t),'bytes':t.stat().st_size})
binding=load(ROOT/'binding.json');pre=load(R/'preflight.json');gateway=load(D/'gateway-config.json');ready=load(R/'renderer-ready.json');observer=load(R/'renderer-observer.json');profile=binding['manifest']['bundles'][0]['launchProfile'];maps=(D/'native-maps.txt').read_text()
checks={'binding_hash_matches_notebook':sha(ROOT/'binding.json')==pre['binding_sha256']==sha(ROOT/'notebook-capsule/binding.json'),'gateway_binding_equal':gateway['binding']==binding,'instance_match':binding['instanceId']==pre['identity']['instanceId']==load(D/'gateway-ready.json').get('identity',load(D/'gateway-ready.json')).get('instanceId'),'single_cuda_bundle':len(binding['manifest']['bundles'])==1 and binding['manifest']['bundles'][0]['backend']=='cuda','actual_model_runtime_match':pre['identity']['modelSha256']==binding['manifest']['model']['sha256'] and pre['identity']['serverSha256']==profile['serverSha256'],'collector_actual_url_match':ready['installed']['url']==ready['installed']['verified_actual_url']==ready['target']['url'],'collector_state_complete':ready['installed']['verified_ready_state']=='complete','observer_source_pin':sha(ROOT/'notebook-capsule/observe_renderer.mjs')=='6aad057fecf81b5cb1870e7192bda60f6102a0b8f77c3547182effe03ba851ca','startup_pin':sha(ROOT/'notebook-capsule/startup_gate.mjs')=='aea146d1af6fa9739c46b003dc0f91b7e70e059b84ffa9b62c296160bae50f2d','renderer_pin':ready['sourceIdentity']==observer['sourceIdentity'],'props4096_single_slot':load(D/'props.json')['default_generation_settings']['n_ctx']==4096 and load(D/'props.json')['total_slots']==1,'recorded_native_identity':gateway['native']['pid']==91393 and str(gateway['native']['startTick'])=='48007096'}
save('identity-review.json',{'checks':checks,'root_input_pins':rootpins,'binding_sha256':sha(ROOT/'binding.json'),'instance':binding['instanceId'],'model_metadata':binding['manifest']['model'],'launch_profile':profile,'required_library_map_names':[{'name':x['name'],'present_in_saved_maps':x['name'] in maps,'admitted_sha256':x['sha256']} for x in profile['requiredLibraries']],'native':gateway['native'],'runtime':pre['identity'],'ready':ready,'vsix_identity':load(ROOT/'vsix-identity.json'),'weight_or_library_content_read':False,'limits':'Saved identities/maps and root preflight are corroboration; worker does not independently hash or load model/library artifacts. Historical check_merged is not represented as a current test.'})
print(json.dumps({'parse':[{'case':x['case'],'event':x['event'],'result':x['stdout'].strip()} for x in parsed],'identity_checks':checks,'gateway_completion_requests':len(ids),'cancelled':sum(x['cancelled'] for x in life),'native_processing':len(proc),'native_released':len(released),'native_compute_sum_ms':sum(times),'cancel_observation_to_key_ms':keyboard['epoch_ms']-observed['epoch_ms']},indent=2))
